language: go
sudo: false
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip

before_install:
  - go get github.com/mitchellh/gox

install:
  - make install

script:
  - make lint
  - make vet
  - make test
  - if [ "${LATEST}" = "true" ]; then gox -os="linux windows netbsd freebsd openbsd plan9" -arch="amd64 386" -output="gtfstidy.`git describe --abbrev=0 --tags --match 'v[0-9.]*'`.{{.OS}}.{{.Arch}}" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
  - if [ "${LATEST}" = "true" ]; then gox -os="darwin" -arch="amd64" -output="gtfstidy.`git describe --abbrev=0 --tags --match 'v[0-9.]*'`.{{.OS}}.{{.Arch}}" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: nNwbPyV0SVS/y6IKnXu9RUFDmxpMZmi1WGY+6/J9C4S2ete1k6GVv8jiG4a/EHddqw7SlemFBzumj7aLCSJ/G2m70OqJeO4U9VpaKy4uweYyfOCTrXDg7Zn1gzp8eNlg+St9dCVpJM78qjWRPUbWoUx1x/l/fbqBZwSeREj70IfQMpu3BsCAclJz/Fl418Jg4MHFaMpODuixZxevYlgQZ13jvQtGIXPqaK06x9rX9ioAGMhwi/zk5zHaDUXYy8hK+z6WAdOCGtsZiJrMhx8nf1KAvicI7uzBdWREqi4e10BVt4fSXhLOU1UYZuoK/xSghnBWKlnOlTHMiSv+5rpFlwUs7y0Qmlao9SCbZUoJxR+EzEWIqxtRG5hWoitSmSvodM2HyE9xNk3lEPCOeEKlrD6zL507/D/Ca+9GPc/AfZ4B9GaQEMuVd7JyEMK9NMmgeuuiKzjQ96JbkxG51Vv8zL6okfTr2/P0xGpDMz3U6ciIEv1+6do5BzxjoD4HPyPrU9DN5W9Q8dbkSlz3qrTSiNYryPZ9SD7K39WKvsxQnfQf8iF49sitUnZZsoB5mlTIXS9fut649lJjymtDbD2hr45eKDQTtjaRiLwx4NlUXARk/2UKaLR4HogxJpkRK5Qse7i/2UaDLDytn8CCZKMIgMVBHJMKYTLHjKexoJgKV38=
  file_glob: true
  file:
  - gtfstidy.*.windows.*.exe
  - gtfstidy.*.darwin.*
  - gtfstidy.*.linux.*
  - gtfstidy.*.freebsd.*
  - gtfstidy.*.openbsd.*
  - gtfstidy.*.netbsd.*
  - gtfstidy.*.plan9.*
  on:
    repo: patrickbr/gtfstidy
    tags: true
    condition: $LATEST = true
